// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgmuwkurwuuebdutwjlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbXV3a3Vyd3V1ZWJkdXR3amxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzQ1MDEsImV4cCI6MjA2NzkxMDUwMX0.RejPJCAlvCI9NY0evr1KkRx9ztJQmX5pY3BSQ6Nz8l8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});